eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${${spring.application.name}:${spring.application.instance_id:${server.port}}:${random.value}}
  client:
    region: default
    registryFetchIntervalSeconds: 5
    availabilityZones:
      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    healthcheck:
      enabled: true